-- 코드를 입력하세요
SELECT 
    COUNT(*) 
    AS USERS 
FROM 
    USER_INFO 
WHERE 
    USER_INFO.JOINED >= '2021-01-01'
    AND USER_INFO.JOINED <= '2021-12-31'
    AND USER_INFO.AGE <= 29 
    AND USER_INFO.AGE >= 20;