-- 코드를 입력하세요
SELECT
    ANIMAL_TYPE,
    COUNT(ANIMAL_TYPE) AS count
FROM
    ANIMAL_INS
GROUP BY
    ANIMAL_TYPE
ORDER BY
    CASE
        WHEN ANIMAL_TYPE = 'Cat' THEN 1
        WHEN ANIMAL_TYPE = 'Dog' THEN 2
        ELSE 3
    END;