-- 코드를 입력하세요
SELECT 
    BOOK_ID, 
    DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM 
    BOOK
WHERE
    BOOK.PUBLISHED_DATE BETWEEN '2021-01-01' AND '2021-12-31'
    AND BOOK.CATEGORY = '인문'
ORDER BY
    PUBLISHED_DATE;